language: node_js
node_js:
    - "0.10"
    - "0.11"
before_script:
    - "./node_modules/.bin/gulp cordova:setup"
after_scripts:
    - "ls -R dist| grep \":$\" | sed -e 's/:$//' -e 's/[^-][^\/]*\// /g' -e 's/^/ /'"